import type { Metadata } from 'next'
import { Sora, Big_Shoulders_Stencil_Display } from 'next/font/google'
import '../globals.css'
import { LanguageProvider } from '@/components/common/LanguageProvider'

const sora = Sora({
	variable: '--font-Sora',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
	params: { lang },
}: Readonly<{
	children: React.ReactNode
	params: { lang: string }
}>) {
	const dictionary = await import(`@/app/dictionaries/${lang}.json`).then(
		(m) => m.default,
	)

	return (
		<html lang={lang}>
			<body
				className={`${sora.variable} font-Sora antialiased bg-main-background`}
			>
				<LanguageProvider dictionary={dictionary}>{children}</LanguageProvider>
			</body>
		</html>
	)
}
